"""This module deals with loading/downloading pyluxcore."""

import pathlib
import os
import itertools
import sys
import subprocess
import shutil
from textwrap import dedent
import base64
import hashlib
from enum import Enum, IntEnum
import types
import json
import configparser
import gzip
import pickle
import re

import bpy
import addon_utils
from _bpy_internal.extensions import wheel_manager

from .. import utils

# The variable PYLUXCORE_VERSION specifies the release version of pyluxcore
# that will be downloaded from PyPi during the standard installation of
# BlendLuxCore. Please update this variable ONLY AFTER the targeted version of
# pyluxcore has been released on PyPi.
PYLUXCORE_VERSION = "2.11.0a6"

# Module folders
ROOT_FOLDER = utils.get_module_path()  # The root dir of the package
WHEEL_DL_FOLDER = ROOT_FOLDER / "wheels"
WHEEL_BACKUP_FOLDER = ROOT_FOLDER / "wheels_backup"

# Extension folder
EXTENSIONS_FOLDER = pathlib.Path(bpy.utils.user_resource("EXTENSIONS"))

# Settings file
SETTINGS_FOLDER = pathlib.Path(
    bpy.utils.user_resource("CONFIG", path="blendluxcore", create=True)
)
SETTINGS_FILENAME = "blc_settings.json"
SETTINGS_FILEPATH = SETTINGS_FOLDER / SETTINGS_FILENAME


def _hash_wheels(wheels):
    """Hash a collection of wheel requirements.

    Wheel requirement valid types are `pathlib.Path` or `str`:
    - Path('/tmp/pyluxcore-2.11.0-cp313-cp313-linux_x86_64.whl')
    - str("pyluxcore==2.10.1")
    - ...

    """
    wheel_hash = hashlib.sha256()
    for wheel in wheels:
        if isinstance(wheel, str):
            wheel_hash.update(wheel.encode())
        elif isinstance(wheel, pathlib.Path):
            with wheel.open("rb") as fwheel:
                wheel_hash = hashlib.file_digest(fwheel, lambda: wheel_hash)
        else:
            raise TypeError("Unhandled Wheel requirement type")
    return wheel_hash.hexdigest()


def _download_wheels(wheel_requirements, no_deps, no_index):
    """Download wheels from wheel requirements."""
    no_deps = bool(no_deps)
    no_index = bool(no_index)

    for wheel_requirement in wheel_requirements:
        command = [
            sys.executable,
            "-m",
            "pip",
            "download",
            "--pre",  # Include pre-releases
            "-d",
            WHEEL_DL_FOLDER,
            wheel_requirement,
        ]
        if no_deps:
            command.append("--no-deps")
        if no_index:
            command.append("--no-index")

        try:
            process = subprocess.run(
                command,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                check=True,
                text=True,
            )
        except subprocess.CalledProcessError as err:
            print(err.stdout)
            raise RuntimeError(
                "[BLC] Failed to download LuxCore "
                f"with return code {err.returncode} "
                f"and return message {err.stdout}"
            ) from err

        if output := process.stdout:
            print("[BLC] Downloading wheel:\n", output)


INSTALL_INFO_HEADER = """\
# This file is intended to store information about pyluxcore installation.
# It is used to determine whether a new installation is necessary at each
# startup.
# Only one entry should be different from 'None', it indicates from which
# source the installation was taken.
#
# This file is automatically generated and should not be edited manually.\n
"""


def _save_installation_info(whl_hash):
    """Save information from the last installation.

    Only one of the supplied arguments should be different from 'None'
    to ensure that the type of installation is saved implicitly as well.
    """
    assert whl_hash
    info_file = ROOT_FOLDER / "pyluxcore_installation_info.txt"
    config = configparser.ConfigParser()
    config["WHEELS"] = {"hash": whl_hash}

    with open(info_file, "w", encoding="utf-8") as f:
        f.write(INSTALL_INFO_HEADER)
        config.write(f)


def _get_installation_info():
    """Check the version to install against the last installed version.

    Compare the version to be installed with the description saved during the
    last install. If they match, installation is skipped for efficiency.
    """
    # Read the file
    info_file = ROOT_FOLDER / "pyluxcore_installation_info.txt"
    print(f"[BLC] Checking installation info ('{info_file}')")

    if not info_file.exists:
        return None

    config = configparser.ConfigParser()
    try:
        config.read([info_file], encoding="utf-8")
    except FileNotFoundError:
        return None
    except configparser.MissingSectionHeaderError:
        print("[BLC] - Warning - Malformed info file")
        return None

    try:
        old_wheel_hash = config["WHEELS"]["hash"]
    except KeyError:
        print("[BLC] Warning - Missing hash in info file content")
        return None

    return old_wheel_hash


def _clear_wheels():
    """Remove wheel files from wheel download folder."""
    files = os.listdir(WHEEL_DL_FOLDER)
    for file in files:
        os.remove(WHEEL_DL_FOLDER / file)


def _backup_wheels():
    """Backup any wheels from a previously successful installation."""
    files = os.listdir(WHEEL_DL_FOLDER)
    for file in files:
        shutil.move(WHEEL_DL_FOLDER / file, WHEEL_BACKUP_FOLDER / file)


def _delete_backup_wheels():
    """Remove all backup wheels from previously successful installation."""
    files = os.listdir(WHEEL_BACKUP_FOLDER)
    for file in files:
        os.remove(WHEEL_BACKUP_FOLDER / file)


def _restore_backup_wheels():
    """Remove backup wheels from previously successful installation.

    Backup wheels are removed from wheel folder.
    """
    files = os.listdir(WHEEL_BACKUP_FOLDER)
    for file in files:
        shutil.move(WHEEL_BACKUP_FOLDER / file, WHEEL_DL_FOLDER / file)


def _check_offline_content(install_offline_folder):
    """Check if offline folder contains something to install."""
    files = os.listdir(install_offline_folder)
    if len(files) == 0:
        raise RuntimeError(
            "BlendLuxCore Installation Error: "
            "The install_offline/ directory exists but is empty!"
        )

    versions = (f.split("-")[1] for f in files if f.startswith("pyluxcore"))
    for version in versions:
        break
    else:
        version = None  # no valid file was found
    return version


def _copy_offline_files(install_offline_folder):
    """Copy offline folder content to wheel folder."""
    files = os.listdir(install_offline_folder)
    for file in files:
        shutil.copy(install_offline_folder / file, WHEEL_DL_FOLDER / file)


def _delete_install_offline(install_offline_folder):
    """Clear offline folder content."""
    files = os.listdir(install_offline_folder)
    for file in files:
        os.remove(install_offline_folder / file)
    os.rmdir(install_offline_folder)


DEFAULT_SETTINGS = {
    "wheel_source": 0,
    "wheel_version": "",
    "path_to_wheel": "",
    "path_to_folder": "",
    "reinstall_upon_reloading": False,
}


def _get_settings():
    """Get pyluxcore loading settings from settings file.

    We first try to import a settings file (typically provided by
    BlendLuxHelper) and, if it fails, we fall back to default settings.
    """
    try:
        with open(SETTINGS_FILEPATH, "r", encoding="utf-8") as fsettings:
            print(f"[BLC] Found wheel settings file ('{SETTINGS_FILEPATH}').")
            return json.load(fsettings)
    except FileNotFoundError:
        # Pass silently: settings file is optional, so not finding it is not an
        # error
        return DEFAULT_SETTINGS
    except OSError as err:
        # Warn and pass
        print(
            "[BLC] Warning: system error while trying to open settings file: "
            f"'{err}'"
        )
        return DEFAULT_SETTINGS
    except (json.JSONDecodeError, UnicodeDecodeError) as err:
        # Warn and pass
        print(f"[BLC] Warning: cannot decode settings file: '{err}'")
        return DEFAULT_SETTINGS


def _update_manifest(wheel_list):
    """Update blender_manifest.toml with wheel info.

    This is intended as a post-update treatment: wheels should have been
    installed before.
    """

    print(f"[BLC] Updating blender manifest")
    pkg_manifest_filepath = ROOT_FOLDER / "blender_manifest.toml"

    # Compute statement
    wheel_abs_paths = list(
        itertools.chain.from_iterable(
            entry[1] for entry in wheel_list if entry[0] == "blendluxcore"
        )
    )
    wheel_rel_paths = ", ".join(
        f'"{path.relative_to(ROOT_FOLDER)}"'
        for path in wheel_abs_paths
    )
    wheel_manifest_statement = f"wheels = [{wheel_rel_paths}]\n"

    # Read manifest
    with open(pkg_manifest_filepath, mode="r", encoding="utf-8") as manifest:
        content = manifest.read()

    # Modify: add wheel statement to manifest content (modify current wheel entry)
    content, number_of_replacements = re.subn(
        r"^\s*wheels\s*=\s*\[.*\]\n?",
        wheel_manifest_statement,
        content,
        flags=re.MULTILINE
    )
    if number_of_replacements != 1:
        print(
            "[BLC] WARNING: inconsistent number of replacements when updating"
            "`wheels` statement in blender_manifest.toml "
            f"({number_of_replacements}) - see file '{pkg_manifest_filepath}'"
        )

    # Write back to file
    with open(pkg_manifest_filepath, mode="w", encoding="utf-8") as manifest:
        manifest.write(content)

    # Create fake wheels
    for path in wheel_abs_paths:
        print(f"[BLC] Creating fake wheel {path.name}")
        path.touch()


def _apply_wheels(p_wheel_list):
    """Wrap call to wheel_manager.apply_action."""

    local_dir = EXTENSIONS_FOLDER / ".local"
    pyver = f"python{sys.version_info.major}.{sys.version_info.minor}"
    site_packages = local_dir / "lib" / pyver / "site-packages"

    wheel_manager.apply_action(
        local_dir=str(local_dir),
        local_dir_site_packages=str(site_packages),
        wheel_list=p_wheel_list,
        error_fn=lambda ex: print("Error:", ex),
        remove_error_fn=lambda filepath, ex: print(
            "Error removing file:", filepath, ex
        ),
        debug=True,
    )


def _install_wheels():
    """Install wheels in Blender from download folder.

    Notes:
    - We use Blender internal feature (wheel_manager.apply_action) to install
      the wheels, see _apply_wheels
    - Once the wheels have been installed, we have to declare them in
      blender_manifest.toml, otherwise the wheels will not be "registered" by
      Blender and any modification on add-ons (install, refresh...) will remove
      them
    - We have to create fake wheels in BLC repo to lure pkg_wheel_filter() (in
      'scripts/addons_core/bl_pkg/bl_extension_ops.py'), as this function will
      check whether the files actually exist and, if not, will uninstall them
    """

    # Get the wheel list
    if not (wheel_list := [("blendluxcore", list(WHEEL_DL_FOLDER.iterdir()))]):
        raise ValueError("[BLC] ERROR - No wheel to install.")

    # Remove previous wheels
    _apply_wheels([("blendluxcore", [])])

    # Install new wheels
    _apply_wheels(wheel_list)

    # Update wheel information in blender_manifest.toml and create fake wheels
    _update_manifest(wheel_list)


class WheelSource(IntEnum):
    """Permitted values for wheel source (from BlendLuxHelper)."""

    PYPI = 0
    LOCAL = 1
    LOCALDEPS = 2


class FetchWheelStatus(IntEnum):
    """Enumeration of return statuses for _fetch_wheels."""

    OK = 0
    ERROR = 1
    CACHE = 2


ENSURE_ERROR_MSG = """\
[BLC] WARNING: Download of pyluxcore not successful... Falling back to wheels
already in cache."""


def _fetch_wheels():
    """Fetch wheels from their locations.

    Fetching means either downloading or copying from local source, depending
    on settings. Wheels are just gathered in a given directory, not installed.
    """
    # Get settings
    settings = _get_settings()

    wheel_source = settings.get("wheel_source", 0)
    reinstall_upon_reloading = bool(
        settings.get("reinstall_upon_reloading", False)
    )
    no_deps = bool(settings.get("no_deps", False))
    no_index = bool(settings.get("no_index", False))

    # Ensure 'wheels' directory exists
    wheels_dir = ROOT_FOLDER / "wheels"
    try:
        print(f"[BLC] Ensuring '{wheels_dir}' exists")
        wheels_dir.mkdir()
    except FileExistsError:
        pass  # Already exists, pass silently

    # Get installation info for comparison in the following steps
    old_wheel_hash = _get_installation_info()

    # Case #1 (standard case): Get wheel from PyPI
    if wheel_source == WheelSource.PYPI:
        # Compute required version
        pyluxcore_version = settings.get("wheel_version") or PYLUXCORE_VERSION

        wheels = [f"pyluxcore=={pyluxcore_version}"]

        print("[BLC] Targeting pyluxcore version:", pyluxcore_version)

    # Case #2: Get from local source (1 file)
    elif wheel_source == WheelSource.LOCAL:
        # Get path to wheel and check consistency
        path_to_wheel = pathlib.Path(settings.get("path_to_wheel", ""))
        if not (path_to_wheel.is_file() and path_to_wheel.is_absolute()):
            print(f"[BLC] Wheel file not found ('{path_to_wheel}')")
            return FetchWheelStatus.ERROR, None

        # Get optional folder with dependencies
        additional_deps = []
        if path_to_wheel_deps_setting := settings.get(
            "path_to_wheel_deps", ""
        ):
            path_to_wheel_deps = pathlib.Path(path_to_wheel_deps_setting)
            if (
                path_to_wheel_deps.is_dir()
                and path_to_wheel_deps.is_absolute()
            ):
                additional_deps = list(path_to_wheel_deps.glob("*.whl"))
            else:
                print(
                    "[BLC] Additional deps folder is not valid "
                    f"('{path_to_wheel_deps}') - Skipping"
                )

        # Set wheel list
        wheels = additional_deps + [path_to_wheel]

        print(
            f"[BLC] Installing local version of pyluxcore ('{path_to_wheel}')"
        )

    # No other case
    else:
        raise ValueError(f"Unhandled wheel source setting ({wheel_source})")

    # Check cache (hash and compare)
    wheel_hash = _hash_wheels(wheels)
    if not reinstall_upon_reloading and wheel_hash == old_wheel_hash:
        # We check there is no desync and pyluxcore is available
        try:
            import pyluxcore
        except ModuleNotFoundError:
            print(
                "[BLC] Warning: pyluxcore should already be installed, "
                "but it is not possible to find it! Reinstalling..."
            )
        else:
            return FetchWheelStatus.CACHE, wheel_hash

    # Download
    _backup_wheels()
    try:
        _download_wheels(wheels, no_deps, no_index)
    except Exception as err:
        print(f"[BLC] Unexpected {err=}, {type(err)=}")
        _clear_wheels()
        _restore_backup_wheels()
        result = FetchWheelStatus.ERROR, None
    else:
        result = FetchWheelStatus.OK, wheel_hash
    finally:
        _delete_backup_wheels()

    return result


def ensure_pyluxcore():
    """Ensure pyluxcore is duly installed.

    This is a prerequisite for being able to import pyluxcore into the rest of
    BlendLuxCore.
    We cannot 'pip install' directly, as it would install pyluxcore
    system-wide, not just in Blender environment. Blender has got its own logic
    for wheel installation, we must rely on it.
    The source which we must fetch wheels from is to be found in settings.
    """

    print("[BLC] Ensuring pyluxcore")

    # Fetch wheels (download or copy from local source, depending on settings)
    # and install them
    fetch_result, wheel_hash = _fetch_wheels()

    if fetch_result == FetchWheelStatus.OK:
        # Install wheels
        print("[BLC] Installing wheel(s)")
        try:
            _install_wheels()
        except ValueError:
            print("[BLC] No wheel installed - BlendLuxCore may be unusable")
        else:
            _save_installation_info(wheel_hash)
    elif fetch_result == FetchWheelStatus.CACHE:
        # Wheels have been found in cache and thus are already installed:
        # => Nothing to do
        print(
            "[BLC] Skipping pyluxcore installation. Similar wheel(s) already "
            "installed."
        )
    elif fetch_result == FetchWheelStatus.ERROR:
        print(ENSURE_ERROR_MSG)
