NONE = "NONE"

# Node tree icons
NTREE_VOLUME = "MOD_FLUIDSIM"
NTREE_MATERIAL = "MATERIAL"
NTREE_TEXTURE = "TEXTURE"

MATERIAL = "MATERIAL"
OBJECT = "OBJECT_DATAMODE"

INFO = "INFO"
WARNING = "ERROR"
ERROR = "CANCEL"

ADD = "ADD"  # + sign
REMOVE = "REMOVE"  # - sign, used to remove one element from a collection
CLEAR = "X"  # x sign, used to clear a link (e.g. the world volume)

ADD_KEYFRAME = "KEY_HLT"
REMOVE_KEYFRAME = "KEY_DEHLT"

LIGHTGROUP = "OUTLINER_OB_LIGHT"
LIGHTGROUP_ENABLED = "OUTLINER_OB_LIGHT"
LIGHTGROUP_DISABLED = "LIGHT"

URL = "URL"
DOWNLOAD = "IMPORT"
COPY_TO_CLIPBOARD = "COPYDOWN"
SHOW_NODETREE = "SCREEN_BACK"
REFRESH = "FILE_REFRESH"  # used in display/denoiser refresh buttons
DUPLICATE = "DUPLICATE"

CAMERA = "CAMERA_DATA"  # this should show a recognizable camera icon. Might need to be changed for 2.80.
WORLD = "WORLD"
IMAGE = "IMAGE_DATA"

EXPANDABLE_CLOSED = "TRIA_RIGHT"
EXPANDABLE_OPENED = "TRIA_DOWN"

FAKE_USER_ON = "FAKE_USER_ON"
FAKE_USER_OFF = "FAKE_USER_OFF"
